  pipelines:
    default:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/solavisetech-migration/aws-etl-tf-python-project.git ## @bitbucket.org follow by your Bitbucket repository path
            - cd aws-etl-tf-python-project.git ## cd followed by your Github repository Name
            - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/felix-momodebe-official/aws-etl-tf-python-project.git ## @github.com followed by your Github repository path